/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaMobilityRouteImport } from './routes/yoga-mobility'
import { Route as VerifyDeviceRouteImport } from './routes/verify-device'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as MealPlansIndexRouteImport } from './routes/meal-plans.index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as CoachesIndexRouteImport } from './routes/coaches.index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as TrainSlugRouteImport } from './routes/train.$slug'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as QuickWorkoutsSlugRouteImport } from './routes/quick-workouts.$slug'
import { Route as QaGluteProgressionRouteImport } from './routes/qa.glute-progression'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as NutritionSlugRouteImport } from './routes/nutrition.$slug'
import { Route as MealPlansSlugRouteImport } from './routes/meal-plans.$slug'
import { Route as ExercisesSlugRouteImport } from './routes/exercises.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CoachesSlugRouteImport } from './routes/coaches.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout_.success'
import { Route as ChallengesSlugRouteImport } from './routes/challenges.$slug'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedMyNutritionRouteImport } from './routes/_authenticated/my-nutrition'
import { Route as AuthenticatedMyLibraryRouteImport } from './routes/_authenticated/my-library'
import { Route as AuthenticatedMeasurementsRouteImport } from './routes/_authenticated/measurements'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedAiCoachRouteImport } from './routes/_authenticated/ai-coach'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedTrainingSlugRouteImport } from './routes/_authenticated/training.$slug'
import { Route as AuthenticatedSharedProgramIdRouteImport } from './routes/_authenticated/shared-program.$id'
import { Route as AuthenticatedAiMealPlanIdRouteImport } from './routes/_authenticated/ai-meal-plan.$id'
import { Route as AuthenticatedAdminImagesRouteImport } from './routes/_authenticated/admin.images'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsRcWebhookRouteImport } from './routes/api/public/payments/rc-webhook'
import { Route as ApiPublicNotificationsStreakReminderRouteImport } from './routes/api/public/notifications/streak-reminder'

const YogaMobilityRoute = YogaMobilityRouteImport.update({
  id: '/yoga-mobility',
  path: '/yoga-mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDeviceRoute = VerifyDeviceRouteImport.update({
  id: '/verify-device',
  path: '/verify-device',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansIndexRoute = MealPlansIndexRouteImport.update({
  id: '/meal-plans/',
  path: '/meal-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIndexRoute = CoachesIndexRouteImport.update({
  id: '/coaches/',
  path: '/coaches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const TrainSlugRoute = TrainSlugRouteImport.update({
  id: '/train/$slug',
  path: '/train/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickWorkoutsSlugRoute = QuickWorkoutsSlugRouteImport.update({
  id: '/quick-workouts/$slug',
  path: '/quick-workouts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QaGluteProgressionRoute = QaGluteProgressionRouteImport.update({
  id: '/qa/glute-progression',
  path: '/qa/glute-progression',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionSlugRoute = NutritionSlugRouteImport.update({
  id: '/nutrition/$slug',
  path: '/nutrition/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansSlugRoute = MealPlansSlugRouteImport.update({
  id: '/meal-plans/$slug',
  path: '/meal-plans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesSlugRoute = ExercisesSlugRouteImport.update({
  id: '/exercises/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesSlugRoute = CoachesSlugRouteImport.update({
  id: '/coaches/$slug',
  path: '/coaches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout_/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuilderRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyNutritionRoute =
  AuthenticatedMyNutritionRouteImport.update({
    id: '/my-nutrition',
    path: '/my-nutrition',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyLibraryRoute = AuthenticatedMyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeasurementsRoute =
  AuthenticatedMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiCoachRoute = AuthenticatedAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingSlugRoute =
  AuthenticatedTrainingSlugRouteImport.update({
    id: '/training/$slug',
    path: '/training/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSharedProgramIdRoute =
  AuthenticatedSharedProgramIdRouteImport.update({
    id: '/shared-program/$id',
    path: '/shared-program/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiMealPlanIdRoute =
  AuthenticatedAiMealPlanIdRouteImport.update({
    id: '/ai-meal-plan/$id',
    path: '/ai-meal-plan/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminImagesRoute =
  AuthenticatedAdminImagesRouteImport.update({
    id: '/admin/images',
    path: '/admin/images',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsRcWebhookRoute =
  ApiPublicPaymentsRcWebhookRouteImport.update({
    id: '/api/public/payments/rc-webhook',
    path: '/api/public/payments/rc-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificationsStreakReminderRoute =
  ApiPublicNotificationsStreakReminderRouteImport.update({
    id: '/api/public/notifications/streak-reminder',
    path: '/api/public/notifications/streak-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRouteWithChildren
  '/careers': typeof CareersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/yoga-mobility': typeof YogaMobilityRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/my-library': typeof AuthenticatedMyLibraryRoute
  '/my-nutrition': typeof AuthenticatedMyNutritionRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/builder/$id': typeof BuilderIdRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/coaches/$slug': typeof CoachesSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/meal-plans/$slug': typeof MealPlansSlugRoute
  '/nutrition/$slug': typeof NutritionSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/qa/glute-progression': typeof QaGluteProgressionRoute
  '/quick-workouts/$slug': typeof QuickWorkoutsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/train/$slug': typeof TrainSlugRoute
  '/builder/': typeof BuilderIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/meal-plans/': typeof MealPlansIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/admin/images': typeof AuthenticatedAdminImagesRoute
  '/ai-meal-plan/$id': typeof AuthenticatedAiMealPlanIdRoute
  '/shared-program/$id': typeof AuthenticatedSharedProgramIdRoute
  '/training/$slug': typeof AuthenticatedTrainingSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/notifications/streak-reminder': typeof ApiPublicNotificationsStreakReminderRoute
  '/api/public/payments/rc-webhook': typeof ApiPublicPaymentsRcWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/yoga-mobility': typeof YogaMobilityRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/my-library': typeof AuthenticatedMyLibraryRoute
  '/my-nutrition': typeof AuthenticatedMyNutritionRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/builder/$id': typeof BuilderIdRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/coaches/$slug': typeof CoachesSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/meal-plans/$slug': typeof MealPlansSlugRoute
  '/nutrition/$slug': typeof NutritionSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/qa/glute-progression': typeof QaGluteProgressionRoute
  '/quick-workouts/$slug': typeof QuickWorkoutsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/train/$slug': typeof TrainSlugRoute
  '/builder': typeof BuilderIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/coaches': typeof CoachesIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/meal-plans': typeof MealPlansIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/admin/images': typeof AuthenticatedAdminImagesRoute
  '/ai-meal-plan/$id': typeof AuthenticatedAiMealPlanIdRoute
  '/shared-program/$id': typeof AuthenticatedSharedProgramIdRoute
  '/training/$slug': typeof AuthenticatedTrainingSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/notifications/streak-reminder': typeof ApiPublicNotificationsStreakReminderRoute
  '/api/public/payments/rc-webhook': typeof ApiPublicPaymentsRcWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRouteWithChildren
  '/careers': typeof CareersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/yoga-mobility': typeof YogaMobilityRoute
  '/_authenticated/ai-coach': typeof AuthenticatedAiCoachRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/measurements': typeof AuthenticatedMeasurementsRoute
  '/_authenticated/my-library': typeof AuthenticatedMyLibraryRoute
  '/_authenticated/my-nutrition': typeof AuthenticatedMyNutritionRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/builder/$id': typeof BuilderIdRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/checkout_/success': typeof CheckoutSuccessRoute
  '/coaches/$slug': typeof CoachesSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/meal-plans/$slug': typeof MealPlansSlugRoute
  '/nutrition/$slug': typeof NutritionSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/qa/glute-progression': typeof QaGluteProgressionRoute
  '/quick-workouts/$slug': typeof QuickWorkoutsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/train/$slug': typeof TrainSlugRoute
  '/builder/': typeof BuilderIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/meal-plans/': typeof MealPlansIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/_authenticated/admin/images': typeof AuthenticatedAdminImagesRoute
  '/_authenticated/ai-meal-plan/$id': typeof AuthenticatedAiMealPlanIdRoute
  '/_authenticated/shared-program/$id': typeof AuthenticatedSharedProgramIdRoute
  '/_authenticated/training/$slug': typeof AuthenticatedTrainingSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/notifications/streak-reminder': typeof ApiPublicNotificationsStreakReminderRoute
  '/api/public/payments/rc-webhook': typeof ApiPublicPaymentsRcWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/builder'
    | '/careers'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/guidelines'
    | '/preview'
    | '/privacy'
    | '/quiz'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/verify-device'
    | '/yoga-mobility'
    | '/ai-coach'
    | '/groups'
    | '/measurements'
    | '/my-library'
    | '/my-nutrition'
    | '/subscription'
    | '/articles/$slug'
    | '/builder/$id'
    | '/challenges/$slug'
    | '/checkout/success'
    | '/coaches/$slug'
    | '/email/unsubscribe'
    | '/exercises/$slug'
    | '/meal-plans/$slug'
    | '/nutrition/$slug'
    | '/programs/$slug'
    | '/qa/glute-progression'
    | '/quick-workouts/$slug'
    | '/recipes/$slug'
    | '/train/$slug'
    | '/builder/'
    | '/challenges/'
    | '/coaches/'
    | '/exercises/'
    | '/meal-plans/'
    | '/nutrition/'
    | '/programs/'
    | '/recipes/'
    | '/admin/images'
    | '/ai-meal-plan/$id'
    | '/shared-program/$id'
    | '/training/$slug'
    | '/lovable/email/suppression'
    | '/api/public/notifications/streak-reminder'
    | '/api/public/payments/rc-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/careers'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/guidelines'
    | '/preview'
    | '/privacy'
    | '/quiz'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/verify-device'
    | '/yoga-mobility'
    | '/ai-coach'
    | '/groups'
    | '/measurements'
    | '/my-library'
    | '/my-nutrition'
    | '/subscription'
    | '/articles/$slug'
    | '/builder/$id'
    | '/challenges/$slug'
    | '/checkout/success'
    | '/coaches/$slug'
    | '/email/unsubscribe'
    | '/exercises/$slug'
    | '/meal-plans/$slug'
    | '/nutrition/$slug'
    | '/programs/$slug'
    | '/qa/glute-progression'
    | '/quick-workouts/$slug'
    | '/recipes/$slug'
    | '/train/$slug'
    | '/builder'
    | '/challenges'
    | '/coaches'
    | '/exercises'
    | '/meal-plans'
    | '/nutrition'
    | '/programs'
    | '/recipes'
    | '/admin/images'
    | '/ai-meal-plan/$id'
    | '/shared-program/$id'
    | '/training/$slug'
    | '/lovable/email/suppression'
    | '/api/public/notifications/streak-reminder'
    | '/api/public/payments/rc-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/app'
    | '/auth'
    | '/builder'
    | '/careers'
    | '/checkout'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/guidelines'
    | '/preview'
    | '/privacy'
    | '/quiz'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/verify-device'
    | '/yoga-mobility'
    | '/_authenticated/ai-coach'
    | '/_authenticated/groups'
    | '/_authenticated/measurements'
    | '/_authenticated/my-library'
    | '/_authenticated/my-nutrition'
    | '/_authenticated/subscription'
    | '/articles/$slug'
    | '/builder/$id'
    | '/challenges/$slug'
    | '/checkout_/success'
    | '/coaches/$slug'
    | '/email/unsubscribe'
    | '/exercises/$slug'
    | '/meal-plans/$slug'
    | '/nutrition/$slug'
    | '/programs/$slug'
    | '/qa/glute-progression'
    | '/quick-workouts/$slug'
    | '/recipes/$slug'
    | '/train/$slug'
    | '/builder/'
    | '/challenges/'
    | '/coaches/'
    | '/exercises/'
    | '/meal-plans/'
    | '/nutrition/'
    | '/programs/'
    | '/recipes/'
    | '/_authenticated/admin/images'
    | '/_authenticated/ai-meal-plan/$id'
    | '/_authenticated/shared-program/$id'
    | '/_authenticated/training/$slug'
    | '/lovable/email/suppression'
    | '/api/public/notifications/streak-reminder'
    | '/api/public/payments/rc-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  CareersRoute: typeof CareersRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  PreviewRoute: typeof PreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyDeviceRoute: typeof VerifyDeviceRoute
  YogaMobilityRoute: typeof YogaMobilityRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ChallengesSlugRoute: typeof ChallengesSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoachesSlugRoute: typeof CoachesSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ExercisesSlugRoute: typeof ExercisesSlugRoute
  MealPlansSlugRoute: typeof MealPlansSlugRoute
  NutritionSlugRoute: typeof NutritionSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  QaGluteProgressionRoute: typeof QaGluteProgressionRoute
  QuickWorkoutsSlugRoute: typeof QuickWorkoutsSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  TrainSlugRoute: typeof TrainSlugRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  CoachesIndexRoute: typeof CoachesIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  MealPlansIndexRoute: typeof MealPlansIndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicNotificationsStreakReminderRoute: typeof ApiPublicNotificationsStreakReminderRoute
  ApiPublicPaymentsRcWebhookRoute: typeof ApiPublicPaymentsRcWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga-mobility': {
      id: '/yoga-mobility'
      path: '/yoga-mobility'
      fullPath: '/yoga-mobility'
      preLoaderRoute: typeof YogaMobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-device': {
      id: '/verify-device'
      path: '/verify-device'
      fullPath: '/verify-device'
      preLoaderRoute: typeof VerifyDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/': {
      id: '/meal-plans/'
      path: '/meal-plans'
      fullPath: '/meal-plans/'
      preLoaderRoute: typeof MealPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/': {
      id: '/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof CoachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/train/$slug': {
      id: '/train/$slug'
      path: '/train/$slug'
      fullPath: '/train/$slug'
      preLoaderRoute: typeof TrainSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-workouts/$slug': {
      id: '/quick-workouts/$slug'
      path: '/quick-workouts/$slug'
      fullPath: '/quick-workouts/$slug'
      preLoaderRoute: typeof QuickWorkoutsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/glute-progression': {
      id: '/qa/glute-progression'
      path: '/qa/glute-progression'
      fullPath: '/qa/glute-progression'
      preLoaderRoute: typeof QaGluteProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/$slug': {
      id: '/nutrition/$slug'
      path: '/nutrition/$slug'
      fullPath: '/nutrition/$slug'
      preLoaderRoute: typeof NutritionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/$slug': {
      id: '/meal-plans/$slug'
      path: '/meal-plans/$slug'
      fullPath: '/meal-plans/$slug'
      preLoaderRoute: typeof MealPlansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$slug': {
      id: '/exercises/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof ExercisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$slug': {
      id: '/coaches/$slug'
      path: '/coaches/$slug'
      fullPath: '/coaches/$slug'
      preLoaderRoute: typeof CoachesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/success': {
      id: '/checkout_/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-nutrition': {
      id: '/_authenticated/my-nutrition'
      path: '/my-nutrition'
      fullPath: '/my-nutrition'
      preLoaderRoute: typeof AuthenticatedMyNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-library': {
      id: '/_authenticated/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof AuthenticatedMyLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/measurements': {
      id: '/_authenticated/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof AuthenticatedMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-coach': {
      id: '/_authenticated/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAiCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training/$slug': {
      id: '/_authenticated/training/$slug'
      path: '/training/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof AuthenticatedTrainingSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shared-program/$id': {
      id: '/_authenticated/shared-program/$id'
      path: '/shared-program/$id'
      fullPath: '/shared-program/$id'
      preLoaderRoute: typeof AuthenticatedSharedProgramIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-meal-plan/$id': {
      id: '/_authenticated/ai-meal-plan/$id'
      path: '/ai-meal-plan/$id'
      fullPath: '/ai-meal-plan/$id'
      preLoaderRoute: typeof AuthenticatedAiMealPlanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/images': {
      id: '/_authenticated/admin/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AuthenticatedAdminImagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/rc-webhook': {
      id: '/api/public/payments/rc-webhook'
      path: '/api/public/payments/rc-webhook'
      fullPath: '/api/public/payments/rc-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsRcWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/streak-reminder': {
      id: '/api/public/notifications/streak-reminder'
      path: '/api/public/notifications/streak-reminder'
      fullPath: '/api/public/notifications/streak-reminder'
      preLoaderRoute: typeof ApiPublicNotificationsStreakReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiCoachRoute: typeof AuthenticatedAiCoachRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedMeasurementsRoute: typeof AuthenticatedMeasurementsRoute
  AuthenticatedMyLibraryRoute: typeof AuthenticatedMyLibraryRoute
  AuthenticatedMyNutritionRoute: typeof AuthenticatedMyNutritionRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedAdminImagesRoute: typeof AuthenticatedAdminImagesRoute
  AuthenticatedAiMealPlanIdRoute: typeof AuthenticatedAiMealPlanIdRoute
  AuthenticatedSharedProgramIdRoute: typeof AuthenticatedSharedProgramIdRoute
  AuthenticatedTrainingSlugRoute: typeof AuthenticatedTrainingSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiCoachRoute: AuthenticatedAiCoachRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedMeasurementsRoute: AuthenticatedMeasurementsRoute,
  AuthenticatedMyLibraryRoute: AuthenticatedMyLibraryRoute,
  AuthenticatedMyNutritionRoute: AuthenticatedMyNutritionRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedAdminImagesRoute: AuthenticatedAdminImagesRoute,
  AuthenticatedAiMealPlanIdRoute: AuthenticatedAiMealPlanIdRoute,
  AuthenticatedSharedProgramIdRoute: AuthenticatedSharedProgramIdRoute,
  AuthenticatedTrainingSlugRoute: AuthenticatedTrainingSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BuilderRouteChildren {
  BuilderIdRoute: typeof BuilderIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderIdRoute: BuilderIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BuilderRoute: BuilderRouteWithChildren,
  CareersRoute: CareersRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  PreviewRoute: PreviewRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyDeviceRoute: VerifyDeviceRoute,
  YogaMobilityRoute: YogaMobilityRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ChallengesSlugRoute: ChallengesSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoachesSlugRoute: CoachesSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ExercisesSlugRoute: ExercisesSlugRoute,
  MealPlansSlugRoute: MealPlansSlugRoute,
  NutritionSlugRoute: NutritionSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  QaGluteProgressionRoute: QaGluteProgressionRoute,
  QuickWorkoutsSlugRoute: QuickWorkoutsSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  TrainSlugRoute: TrainSlugRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  CoachesIndexRoute: CoachesIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  MealPlansIndexRoute: MealPlansIndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicNotificationsStreakReminderRoute:
    ApiPublicNotificationsStreakReminderRoute,
  ApiPublicPaymentsRcWebhookRoute: ApiPublicPaymentsRcWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
