UPDATE public.foods SET name_no = 'Kyllingbryst (kokt)', name_es = 'Pechuga de pollo (cocida)', name_pt = 'Peito de frango (cozido)' WHERE name = 'Chicken breast (cooked)';
UPDATE public.foods SET name_no = 'Kyllinglår (kokt, uten skinn)', name_es = 'Muslo de pollo (cocido, sin piel)', name_pt = 'Coxa de frango (cozida, sem pele)' WHERE name = 'Chicken thigh (cooked, skinless)';
UPDATE public.foods SET name_no = 'Kjøttdeig 90/10 (stekt)', name_es = 'Carne molida 90/10 (cocida)', name_pt = 'Carne moída 90/10 (cozida)' WHERE name = 'Ground beef 90/10 (cooked)';
UPDATE public.foods SET name_no = 'Mørbradbiff (stekt)', name_es = 'Filete de solomillo (cocido)', name_pt = 'Bife de alcatra (grelhado)' WHERE name = 'Beef sirloin steak (cooked)';
UPDATE public.foods SET name_no = 'Svinefilet (stekt)', name_es = 'Lomo de cerdo (cocido)', name_pt = 'Filé mignon suíno (cozido)' WHERE name = 'Pork tenderloin (cooked)';
UPDATE public.foods SET name_no = 'Laks (kokt)', name_es = 'Salmón (cocido)', name_pt = 'Salmão (cozido)' WHERE name = 'Salmon (cooked)';
UPDATE public.foods SET name_no = 'Tunfisk (i vann)', name_es = 'Atún (en agua)', name_pt = 'Atum (em água)' WHERE name = 'Tuna (canned in water)';
UPDATE public.foods SET name_no = 'Torsk (kokt)', name_es = 'Bacalao (cocido)', name_pt = 'Bacalhau (cozido)' WHERE name = 'Cod (cooked)';
UPDATE public.foods SET name_no = 'Reker (kokte)', name_es = 'Camarones (cocidos)', name_pt = 'Camarão (cozido)' WHERE name = 'Shrimp (cooked)';
UPDATE public.foods SET name_no = 'Helt egg (stort)', name_es = 'Huevo entero (grande)', name_pt = 'Ovo inteiro (grande)' WHERE name = 'Whole egg (large)';
UPDATE public.foods SET name_no = 'Eggehviter', name_es = 'Claras de huevo', name_pt = 'Claras de ovo' WHERE name = 'Egg whites';
UPDATE public.foods SET name_no = 'Myseproteinpulver', name_es = 'Proteína de suero en polvo', name_pt = 'Whey protein em pó' WHERE name = 'Whey protein powder';
UPDATE public.foods SET name_no = 'Kaseinproteinpulver', name_es = 'Proteína caseína en polvo', name_pt = 'Caseína em pó' WHERE name = 'Casein protein powder';
UPDATE public.foods SET name_no = 'Tofu (fast)', name_es = 'Tofu (firme)', name_pt = 'Tofu (firme)' WHERE name = 'Tofu (firm)';
UPDATE public.foods SET name_no = 'Kalkunbryst (kokt)', name_es = 'Pechuga de pavo (cocida)', name_pt = 'Peito de peru (cozido)' WHERE name = 'Turkey breast (cooked)';
UPDATE public.foods SET name_no = 'Hvit ris (kokt)', name_es = 'Arroz blanco (cocido)', name_pt = 'Arroz branco (cozido)' WHERE name = 'White rice (cooked)';
UPDATE public.foods SET name_no = 'Brun ris (kokt)', name_es = 'Arroz integral (cocido)', name_pt = 'Arroz integral (cozido)' WHERE name = 'Brown rice (cooked)';
UPDATE public.foods SET name_no = 'Havregryn (tørre)', name_es = 'Avena en hojuelas (seca)', name_pt = 'Aveia em flocos (seca)' WHERE name = 'Rolled oats (dry)';
UPDATE public.foods SET name_no = 'Søtpotet (kokt)', name_es = 'Batata (cocida)', name_pt = 'Batata-doce (cozida)' WHERE name = 'Sweet potato (cooked)';
UPDATE public.foods SET name_no = 'Hvit potet (kokt)', name_es = 'Patata blanca (hervida)', name_pt = 'Batata branca (cozida)' WHERE name = 'White potato (boiled)';
UPDATE public.foods SET name_no = 'Pasta (kokt)', name_es = 'Pasta (cocida)', name_pt = 'Massa (cozida)' WHERE name = 'Pasta (cooked)';
UPDATE public.foods SET name_no = 'Quinoa (kokt)', name_es = 'Quinoa (cocida)', name_pt = 'Quinoa (cozida)' WHERE name = 'Quinoa (cooked)';
UPDATE public.foods SET name_no = 'Couscous (kokt)', name_es = 'Cuscús (cocido)', name_pt = 'Cuscuz (cozido)' WHERE name = 'Couscous (cooked)';
UPDATE public.foods SET name_no = 'Tortillalefse (hvete)', name_es = 'Tortilla de harina', name_pt = 'Tortilla de trigo' WHERE name = 'Tortilla wrap (flour)';
UPDATE public.foods SET name_no = 'Bagel (naturell)', name_es = 'Bagel (natural)', name_pt = 'Bagel (simples)' WHERE name = 'Bagel (plain)';
UPDATE public.foods SET name_no = 'Riskaker', name_es = 'Tortitas de arroz', name_pt = 'Bolinhos de arroz (crackers)' WHERE name = 'Rice cakes';
UPDATE public.foods SET name_no = 'Sorte bønner (kokte)', name_es = 'Frijoles negros (cocidos)', name_pt = 'Feijão preto (cozido)' WHERE name = 'Black beans (cooked)';
UPDATE public.foods SET name_no = 'Kidneybønner (kokte)', name_es = 'Frijoles rojos (cocidos)', name_pt = 'Feijão vermelho (cozido)' WHERE name = 'Kidney beans (cooked)';
UPDATE public.foods SET name_no = 'Linser (kokte)', name_es = 'Lentejas (cocidas)', name_pt = 'Lentilhas (cozidas)' WHERE name = 'Lentils (cooked)';
UPDATE public.foods SET name_no = 'Kikerter (kokte)', name_es = 'Garbanzos (cocidos)', name_pt = 'Grão-de-bico (cozido)' WHERE name = 'Chickpeas (cooked)';
UPDATE public.foods SET name_no = 'Feijão (brasilianske sorte bønner)', name_es = 'Feijão (frijoles negros brasileños)', name_pt = 'Feijão preto' WHERE name = 'Feijão (Brazilian black beans)';
UPDATE public.foods SET name_no = 'Gresk yoghurt (0% fett)', name_es = 'Yogur griego (0% grasa)', name_pt = 'Iogurte grego (0% gordura)' WHERE name = 'Greek yogurt (0% fat)';
UPDATE public.foods SET name_no = 'Gresk yoghurt (2% fett)', name_es = 'Yogur griego (2% grasa)', name_pt = 'Iogurte grego (2% gordura)' WHERE name = 'Greek yogurt (2% fat)';
UPDATE public.foods SET name_no = 'Cottage cheese (mager)', name_es = 'Requesón (bajo en grasa)', name_pt = 'Queijo cottage (magro)' WHERE name = 'Cottage cheese (low-fat)';
UPDATE public.foods SET name_no = 'Mozzarellaost', name_es = 'Queso mozzarella', name_pt = 'Queijo mozzarella' WHERE name = 'Mozzarella cheese';
UPDATE public.foods SET name_no = 'Olivenolje', name_es = 'Aceite de oliva', name_pt = 'Azeite de oliva' WHERE name = 'Olive oil';
UPDATE public.foods SET name_no = 'Kokosolje', name_es = 'Aceite de coco', name_pt = 'Óleo de coco' WHERE name = 'Coconut oil';
UPDATE public.foods SET name_no = 'Açaí-puré (usøtet)', name_es = 'Pulpa de açaí (sin azúcar)', name_pt = 'Polpa de açaí (sem açúcar)' WHERE name = 'Açaí pulp (unsweetened)';
UPDATE public.foods SET name_no = 'Brokkoli (kokt)', name_es = 'Brócoli (cocido)', name_pt = 'Brócolis (cozido)' WHERE name = 'Broccoli (cooked)';
UPDATE public.foods SET name_no = 'Spinat (rå)', name_es = 'Espinacas (crudas)', name_pt = 'Espinafre (cru)' WHERE name = 'Spinach (raw)';
UPDATE public.foods SET name_no = 'Gulrøtter (rå)', name_es = 'Zanahorias (crudas)', name_pt = 'Cenouras (cruas)' WHERE name = 'Carrots (raw)';
UPDATE public.foods SET name_no = 'Salat (romano)', name_es = 'Lechuga (romana)', name_pt = 'Alface (romana)' WHERE name = 'Lettuce (romaine)';
UPDATE public.foods SET name_no = 'Asparges (kokt)', name_es = 'Espárragos (cocidos)', name_pt = 'Aspargos (cozidos)' WHERE name = 'Asparagus (cooked)';
UPDATE public.foods SET name_no = 'Blomkål (kokt)', name_es = 'Coliflor (cocida)', name_pt = 'Couve-flor (cozida)' WHERE name = 'Cauliflower (cooked)';
UPDATE public.foods SET name_no = 'Squash (kokt)', name_es = 'Calabacín (cocido)', name_pt = 'Abobrinha (cozida)' WHERE name = 'Zucchini (cooked)';
UPDATE public.foods SET name_no = 'Grønnkål (kokt)', name_es = 'Col rizada (cocida)', name_pt = 'Couve (cozida)' WHERE name = 'Kale (cooked)';
UPDATE public.foods SET name_no = 'Proteinbar (snitt)', name_es = 'Barra de proteína (promedio)', name_pt = 'Barra de proteína (média)' WHERE name = 'Protein bar (avg)';
UPDATE public.foods SET name_no = 'Mørk sjokolade 70%', name_es = 'Chocolate negro 70%', name_pt = 'Chocolate amargo 70%' WHERE name = 'Dark chocolate 70%';
UPDATE public.foods SET name_no = 'Melkesjokolade', name_es = 'Chocolate con leche', name_pt = 'Chocolate ao leite' WHERE name = 'Milk chocolate';
UPDATE public.foods SET name_no = 'Potetgull', name_es = 'Patatas fritas de bolsa', name_pt = 'Batata chips' WHERE name = 'Potato chips';
UPDATE public.foods SET name_no = 'Popcorn (luftpoppet)', name_es = 'Palomitas (sin aceite)', name_pt = 'Pipoca (sem óleo)' WHERE name = 'Popcorn (air popped)';
UPDATE public.foods SET name_no = 'Hummus', name_es = 'Hummus', name_pt = 'Homus' WHERE name = 'Hummus';
UPDATE public.foods SET name_no = 'Granola', name_es = 'Granola', name_pt = 'Granola' WHERE name = 'Granola';
UPDATE public.foods SET name_no = 'Honning', name_es = 'Miel', name_pt = 'Mel' WHERE name = 'Honey';
UPDATE public.foods SET name_no = 'Lønnesirup', name_es = 'Jarabe de arce', name_pt = 'Xarope de bordo' WHERE name = 'Maple syrup';
UPDATE public.foods SET name_no = 'Kaffe (svart)', name_es = 'Café (negro)', name_pt = 'Café (preto)' WHERE name = 'Coffee (black)';
UPDATE public.foods SET name_no = 'Laks (rå, norsk)', name_es = 'Salmón (crudo, noruego)', name_pt = 'Salmão (cru, norueguês)' WHERE name = 'Salmon (raw, Norwegian)';
UPDATE public.foods SET name_no = 'Rugbrød (norsk)', name_es = 'Pan de centeno (noruego)', name_pt = 'Pão de centeio (norueguês)' WHERE name = 'Rye bread (Norwegian)';
UPDATE public.foods SET name_no = 'Brunost', name_es = 'Brunost (queso marrón noruego)', name_pt = 'Brunost (queijo marrom norueguês)' WHERE name = 'Brunost (brown cheese)';
UPDATE public.foods SET name_no = 'McDonald''s Big Mac', name_es = 'Big Mac de McDonald''s', name_pt = 'Big Mac do McDonald''s' WHERE name = 'McDonald''s Big Mac';
UPDATE public.foods SET name_no = 'Pizzastykke (ost)', name_es = 'Porción de pizza (queso)', name_pt = 'Fatia de pizza (queijo)' WHERE name = 'Pizza slice (cheese)';
UPDATE public.foods SET name_no = 'Pommes frites', name_es = 'Papas fritas', name_pt = 'Batata frita' WHERE name = 'French fries';
UPDATE public.foods SET name_no = 'Sushi (California-rull)', name_es = 'Sushi (rollo California)', name_pt = 'Sushi (California roll)' WHERE name = 'Sushi (California roll)';
UPDATE public.foods SET name_no = 'Cæsarsalat med kylling', name_es = 'Ensalada César con pollo', name_pt = 'Salada Caesar com frango' WHERE name = 'Chicken caesar salad';
UPDATE public.foods SET name_no = 'Kreatinmonohydrat', name_es = 'Creatina monohidrato', name_pt = 'Creatina monohidratada' WHERE name = 'Creatine monohydrate';
UPDATE public.foods SET name_no = 'BCAA-pulver', name_es = 'BCAA en polvo', name_pt = 'BCAA em pó' WHERE name = 'BCAA powder';
UPDATE public.foods SET name_no = 'Tilapia (kokt)', name_es = 'Tilapia (cocida)', name_pt = 'Tilápia (cozida)' WHERE name = 'Tilapia (cooked)';
UPDATE public.foods SET name_no = 'Kveite (kokt)', name_es = 'Halibut (cocido)', name_pt = 'Halibute (cozido)' WHERE name = 'Halibut (cooked)';
UPDATE public.foods SET name_no = 'Sardiner (i olivenolje)', name_es = 'Sardinas (en aceite de oliva)', name_pt = 'Sardinha (em azeite)' WHERE name = 'Sardines (in olive oil)';
UPDATE public.foods SET name_no = 'Makrell (kokt)', name_es = 'Caballa (cocida)', name_pt = 'Cavala (cozida)' WHERE name = 'Mackerel (cooked)';
UPDATE public.foods SET name_no = 'Havabbor (kokt)', name_es = 'Lubina (cocida)', name_pt = 'Robalo (cozido)' WHERE name = 'Sea bass (cooked)';
UPDATE public.foods SET name_no = 'Ørret (kokt)', name_es = 'Trucha (cocida)', name_pt = 'Truta (cozida)' WHERE name = 'Trout (cooked)';
UPDATE public.foods SET name_no = 'Blåskjell (kokte)', name_es = 'Mejillones (cocidos)', name_pt = 'Mexilhões (cozidos)' WHERE name = 'Mussels (cooked)';
UPDATE public.foods SET name_no = 'Kamskjell (kokte)', name_es = 'Vieiras (cocidas)', name_pt = 'Vieiras (cozidas)' WHERE name = 'Scallops (cooked)';
UPDATE public.foods SET name_no = 'Krabbekjøtt (kokt)', name_es = 'Carne de cangrejo (cocida)', name_pt = 'Carne de caranguejo (cozida)' WHERE name = 'Crab meat (cooked)';
UPDATE public.foods SET name_no = 'Hummer (kokt)', name_es = 'Langosta (cocida)', name_pt = 'Lagosta (cozida)' WHERE name = 'Lobster (cooked)';
UPDATE public.foods SET name_no = 'Blekksprut (grillet)', name_es = 'Calamares (a la parrilla)', name_pt = 'Lula (grelhada)' WHERE name = 'Calamari (grilled)';
UPDATE public.foods SET name_no = 'Fish and chips', name_es = 'Pescado con patatas fritas', name_pt = 'Peixe com fritas' WHERE name = 'Fish and chips';
UPDATE public.foods SET name_no = 'Lammekotelett (stekt)', name_es = 'Chuleta de cordero (cocida)', name_pt = 'Costeleta de cordeiro (cozida)' WHERE name = 'Lamb chop (cooked)';
UPDATE public.foods SET name_no = 'Entrecôte (stekt)', name_es = 'Chuletón (cocido)', name_pt = 'Bife ancho (grelhado)' WHERE name = 'Ribeye steak (cooked)';
UPDATE public.foods SET name_no = 'Oksebryst (kokt)', name_es = 'Pecho de res (cocido)', name_pt = 'Peito bovino (cozido)' WHERE name = 'Beef brisket (cooked)';
UPDATE public.foods SET name_no = 'Kjøttboller (kokte)', name_es = 'Albóndigas de res (cocidas)', name_pt = 'Almôndegas bovinas (cozidas)' WHERE name = 'Beef meatballs (cooked)';
UPDATE public.foods SET name_no = 'Kalkundeig (stekt)', name_es = 'Pavo molido (cocido)', name_pt = 'Peru moído (cozido)' WHERE name = 'Ground turkey (cooked)';
UPDATE public.foods SET name_no = 'Bacon (stekt)', name_es = 'Tocino (cocido)', name_pt = 'Bacon (frito)' WHERE name = 'Bacon (cooked)';
UPDATE public.foods SET name_no = 'Skinke (delikatesse)', name_es = 'Jamón (fiambre)', name_pt = 'Presunto (fatiado)' WHERE name = 'Ham (deli)';
UPDATE public.foods SET name_no = 'Svinepølse (stekt)', name_es = 'Salchicha de cerdo (cocida)', name_pt = 'Linguiça suína (cozida)' WHERE name = 'Pork sausage (cooked)';
UPDATE public.foods SET name_no = 'Spekeskinke (prosciutto)', name_es = 'Prosciutto', name_pt = 'Prosciutto' WHERE name = 'Prosciutto';
UPDATE public.foods SET name_no = 'Spaghetti bolognese', name_es = 'Espaguetis a la boloñesa', name_pt = 'Espaguete à bolonhesa' WHERE name = 'Spaghetti bolognese';
UPDATE public.foods SET name_no = 'Lasagne (okse)', name_es = 'Lasaña (de res)', name_pt = 'Lasanha (de carne)' WHERE name = 'Lasagna (beef)';
UPDATE public.foods SET name_no = 'Kyllingcurry (med saus)', name_es = 'Curry de pollo (con salsa)', name_pt = 'Frango ao curry (com molho)' WHERE name = 'Chicken curry (with sauce)';
UPDATE public.foods SET name_no = 'Wok med okse og grønnsaker', name_es = 'Salteado de res con verduras', name_pt = 'Carne bovina refogada com legumes' WHERE name = 'Beef stir fry with vegetables';
UPDATE public.foods SET name_no = 'Wok med kylling og grønnsaker', name_es = 'Salteado de pollo con verduras', name_pt = 'Frango refogado com legumes' WHERE name = 'Chicken stir fry with vegetables';
UPDATE public.foods SET name_no = 'Cheeseburger (hurtigmat)', name_es = 'Hamburguesa con queso (comida rápida)', name_pt = 'Cheeseburger (fast food)' WHERE name = 'Cheeseburger (fast food)';
UPDATE public.foods SET name_no = 'Taco med okse', name_es = 'Taco de res', name_pt = 'Taco de carne' WHERE name = 'Beef taco';
UPDATE public.foods SET name_no = 'Kyllingfajitas', name_es = 'Fajitas de pollo', name_pt = 'Fajitas de frango' WHERE name = 'Chicken fajitas';
UPDATE public.foods SET name_no = 'Sushi (laksenigiri)', name_es = 'Sushi (nigiri de salmón)', name_pt = 'Sushi (niguiri de salmão)' WHERE name = 'Sushi (salmon nigiri)';
UPDATE public.foods SET name_no = 'Sushi (sterk tunfiskrull)', name_es = 'Sushi (rollo de atún picante)', name_pt = 'Sushi (roll de atum picante)' WHERE name = 'Sushi (spicy tuna roll)';
UPDATE public.foods SET name_no = 'Pad thai (kylling)', name_es = 'Pad thai (pollo)', name_pt = 'Pad thai (frango)' WHERE name = 'Pad thai (chicken)';
UPDATE public.foods SET name_no = 'Kylling tikka masala', name_es = 'Pollo tikka masala', name_pt = 'Frango tikka masala' WHERE name = 'Chicken tikka masala';
UPDATE public.foods SET name_no = 'Pizzastykke med pepperoni', name_es = 'Porción de pizza de pepperoni', name_pt = 'Fatia de pizza de pepperoni' WHERE name = 'Pepperoni pizza slice';
UPDATE public.foods SET name_no = 'Kyllingshawarma-wrap', name_es = 'Wrap de shawarma de pollo', name_pt = 'Wrap de shawarma de frango' WHERE name = 'Chicken shawarma wrap';
UPDATE public.foods SET name_no = 'Burrito med okse', name_es = 'Burrito de res', name_pt = 'Burrito de carne' WHERE name = 'Beef burrito';
UPDATE public.foods SET name_no = 'Falafel (fritert)', name_es = 'Falafel (frito)', name_pt = 'Falafel (frito)' WHERE name = 'Falafel (fried)';
UPDATE public.foods SET name_no = 'Grillet kyllingbryst-middag (med ris og grønnsaker)', name_es = 'Cena de pechuga de pollo a la parrilla (con arroz y verduras)', name_pt = 'Jantar de peito de frango grelhado (com arroz e legumes)' WHERE name = 'Grilled chicken breast dinner (with rice & veg)';
UPDATE public.foods SET name_no = 'Laksemiddag (med potet og grønnsaker)', name_es = 'Cena de salmón (con patata y verduras)', name_pt = 'Jantar de salmão (com batata e legumes)' WHERE name = 'Salmon dinner (with potato & veg)';
UPDATE public.foods SET name_no = 'Gresk salat', name_es = 'Ensalada griega', name_pt = 'Salada grega' WHERE name = 'Greek salad';
UPDATE public.foods SET name_no = 'Cobb-salat', name_es = 'Ensalada Cobb', name_pt = 'Salada Cobb' WHERE name = 'Cobb salad';
UPDATE public.foods SET name_no = 'Tunfisksalat (med majones)', name_es = 'Ensalada de atún (con mayonesa)', name_pt = 'Salada de atum (com maionese)' WHERE name = 'Tuna salad (with mayo)';
UPDATE public.foods SET name_no = 'Kokke-salat', name_es = 'Ensalada del chef', name_pt = 'Salada do chef' WHERE name = 'Chef salad';
UPDATE public.foods SET name_no = 'Quinoa-salat', name_es = 'Ensalada de quinoa', name_pt = 'Salada de quinoa' WHERE name = 'Quinoa salad';
UPDATE public.foods SET name_no = 'Caprese-salat', name_es = 'Ensalada Caprese', name_pt = 'Salada Caprese' WHERE name = 'Caprese salad';
UPDATE public.foods SET name_no = 'Hagesalat (uten dressing)', name_es = 'Ensalada de la huerta (sin aderezo)', name_pt = 'Salada verde (sem molho)' WHERE name = 'Garden salad (no dressing)';
UPDATE public.foods SET name_no = 'Grønnkålsalat', name_es = 'Ensalada de col rizada', name_pt = 'Salada de couve' WHERE name = 'Kale salad';
UPDATE public.foods SET name_no = 'Cæsardressing', name_es = 'Aderezo César', name_pt = 'Molho Caesar' WHERE name = 'Caesar dressing';
UPDATE public.foods SET name_no = 'Ranch-dressing', name_es = 'Aderezo ranch', name_pt = 'Molho ranch' WHERE name = 'Ranch dressing';
UPDATE public.foods SET name_no = 'Potetmos', name_es = 'Puré de patatas', name_pt = 'Purê de batatas' WHERE name = 'Mashed potatoes';
UPDATE public.foods SET name_no = 'Ovnsbakte grønnsaker', name_es = 'Verduras asadas', name_pt = 'Legumes assados' WHERE name = 'Roasted vegetables';
UPDATE public.foods SET name_no = 'Gnocchi (kokt)', name_es = 'Ñoquis (cocidos)', name_pt = 'Nhoque (cozido)' WHERE name = 'Gnocchi (cooked)';
UPDATE public.foods SET name_no = 'Ramen (med kraft)', name_es = 'Ramen (con caldo)', name_pt = 'Ramen (com caldo)' WHERE name = 'Ramen (with broth)';
UPDATE public.foods SET name_no = 'Baked beans', name_es = 'Frijoles horneados', name_pt = 'Feijão cozido (baked beans)' WHERE name = 'Baked beans';
UPDATE public.foods SET name_no = 'Maiskolbe', name_es = 'Mazorca de maíz', name_pt = 'Milho na espiga' WHERE name = 'Corn on the cob';
UPDATE public.foods SET name_no = 'Grønne bønner (kokte)', name_es = 'Judías verdes (cocidas)', name_pt = 'Vagem (cozida)' WHERE name = 'Green beans (cooked)';
UPDATE public.foods SET name_no = 'Erter (kokte)', name_es = 'Guisantes (cocidos)', name_pt = 'Ervilhas (cozidas)' WHERE name = 'Peas (cooked)';
UPDATE public.foods SET name_no = 'Løk (rå)', name_es = 'Cebolla (cruda)', name_pt = 'Cebola (crua)' WHERE name = 'Onion (raw)';
UPDATE public.foods SET name_no = 'Sopp (kokt)', name_es = 'Champiñones (cocidos)', name_pt = 'Cogumelos (cozidos)' WHERE name = 'Mushrooms (cooked)';
UPDATE public.foods SET name_no = 'Rødbete (kokt)', name_es = 'Remolacha (cocida)', name_pt = 'Beterraba (cozida)' WHERE name = 'Beetroot (cooked)';
UPDATE public.foods SET name_no = 'Edamame (kokt)', name_es = 'Edamame (cocido)', name_pt = 'Edamame (cozido)' WHERE name = 'Edamame (cooked)';
UPDATE public.foods SET name_no = 'Kyllingnudelsuppe', name_es = 'Sopa de fideos con pollo', name_pt = 'Sopa de macarrão com frango' WHERE name = 'Chicken noodle soup';
UPDATE public.foods SET name_no = 'Tomatsuppe', name_es = 'Sopa de tomate', name_pt = 'Sopa de tomate' WHERE name = 'Tomato soup';
UPDATE public.foods SET name_no = 'Minestronesuppe', name_es = 'Sopa minestrone', name_pt = 'Sopa minestrone' WHERE name = 'Minestrone soup';
UPDATE public.foods SET name_no = 'Gresskarsuppe', name_es = 'Sopa de calabaza', name_pt = 'Sopa de abóbora' WHERE name = 'Pumpkin soup';
UPDATE public.foods SET name_no = 'Misosuppe', name_es = 'Sopa de miso', name_pt = 'Sopa de missô' WHERE name = 'Miso soup';
UPDATE public.foods SET name_no = 'Pannekaker (naturell)', name_es = 'Panqueques (natural)', name_pt = 'Panquecas (simples)' WHERE name = 'Pancakes (plain)';
UPDATE public.foods SET name_no = 'Vafler', name_es = 'Gofres', name_pt = 'Waffles' WHERE name = 'Waffles';
UPDATE public.foods SET name_no = 'Arme riddere (french toast)', name_es = 'Tostadas francesas', name_pt = 'Rabanada (french toast)' WHERE name = 'French toast';
UPDATE public.foods SET name_no = 'Omelett (2 egg, naturell)', name_es = 'Tortilla francesa (2 huevos, natural)', name_pt = 'Omelete (2 ovos, simples)' WHERE name = 'Omelette (2 eggs, plain)';
UPDATE public.foods SET name_no = 'Frokostburrito (pølse og egg)', name_es = 'Burrito de desayuno (salchicha y huevo)', name_pt = 'Burrito de café da manhã (linguiça e ovo)' WHERE name = 'Breakfast burrito (sausage & egg)';
UPDATE public.foods SET name_no = 'Croissant (smør)', name_es = 'Croissant (mantequilla)', name_pt = 'Croissant (manteiga)' WHERE name = 'Croissant (butter)';
UPDATE public.foods SET name_no = 'Müsli (tørr)', name_es = 'Muesli (seco)', name_pt = 'Muesli (seco)' WHERE name = 'Muesli (dry)';
UPDATE public.foods SET name_no = 'Smoothiebolle (blandede bær)', name_es = 'Bowl de smoothie (frutos rojos)', name_pt = 'Bowl de smoothie (frutas vermelhas)' WHERE name = 'Smoothie bowl (mixed berry)';
UPDATE public.foods SET name_no = 'Sjokolademelk', name_es = 'Leche con chocolate', name_pt = 'Leite com chocolate' WHERE name = 'Chocolate milk';
UPDATE public.foods SET name_no = 'Studentblanding', name_es = 'Mezcla de frutos secos', name_pt = 'Mix de castanhas e frutas secas' WHERE name = 'Trail mix';
UPDATE public.foods SET name_no = 'Tørket oksekjøtt (jerky)', name_es = 'Cecina de res', name_pt = 'Carne seca (jerky)' WHERE name = 'Beef jerky';
UPDATE public.foods SET name_no = 'String cheese (mozzarella)', name_es = 'Queso en tiras (mozzarella)', name_pt = 'Queijo em palito (mozzarella)' WHERE name = 'String cheese (mozzarella)';
UPDATE public.foods SET name_no = 'Kringler (harde)', name_es = 'Pretzels (duros)', name_pt = 'Pretzels (duros)' WHERE name = 'Pretzels (hard)';
UPDATE public.foods SET name_no = 'Saltkjeks', name_es = 'Galletas saladas', name_pt = 'Biscoitos salgados' WHERE name = 'Salted crackers';
UPDATE public.foods SET name_no = 'Riskjeks', name_es = 'Galletas de arroz', name_pt = 'Biscoitos de arroz' WHERE name = 'Rice crackers';
UPDATE public.foods SET name_no = 'Iskrem (vanilje)', name_es = 'Helado (vainilla)', name_pt = 'Sorvete (baunilha)' WHERE name = 'Ice cream (vanilla)';
UPDATE public.foods SET name_no = 'Frossenyoghurt', name_es = 'Yogur helado', name_pt = 'Iogurte congelado' WHERE name = 'Frozen yogurt';
UPDATE public.foods SET name_no = 'Brownie', name_es = 'Brownie', name_pt = 'Brownie' WHERE name = 'Brownie';
UPDATE public.foods SET name_no = 'Sjokoladecookie', name_es = 'Galleta con chispas de chocolate', name_pt = 'Cookie com gotas de chocolate' WHERE name = 'Chocolate chip cookie';
UPDATE public.foods SET name_no = 'Kaffe med melk', name_es = 'Café con leche', name_pt = 'Café com leite' WHERE name = 'Coffee with milk';
UPDATE public.foods SET name_no = 'Cappuccino', name_es = 'Capuchino', name_pt = 'Cappuccino' WHERE name = 'Cappuccino';
UPDATE public.foods SET name_no = 'Kombucha', name_es = 'Kombucha', name_pt = 'Kombucha' WHERE name = 'Kombucha';
UPDATE public.foods SET name_no = 'Sportsdrikk (Gatorade)', name_es = 'Bebida deportiva (Gatorade)', name_pt = 'Bebida esportiva (Gatorade)' WHERE name = 'Sports drink (Gatorade)';
UPDATE public.foods SET name_no = 'Energidrikk (Red Bull)', name_es = 'Bebida energética (Red Bull)', name_pt = 'Bebida energética (Red Bull)' WHERE name = 'Energy drink (Red Bull)';
UPDATE public.foods SET name_no = 'Granateplekjerner', name_es = 'Semillas de granada', name_pt = 'Sementes de romã' WHERE name = 'Pomegranate seeds';
UPDATE public.foods SET name_no = 'Dadler (Medjool)', name_es = 'Dátiles (Medjool)', name_pt = 'Tâmaras (Medjool)' WHERE name = 'Dates (Medjool)';